export const VOTE_STORY_REQUEST = 'VOTE_STORY_REQUEST';
export const VOTE_STORY_SUCCESS = 'VOTE_STORY_SUCCESS';
export const VOTE_STORY_FAILURE = 'VOTE_STORY_REQUEST';

export const GET_VOTES_REQUEST = 'GET_VOTES_REQUEST';
export const GET_VOTES_SUCCESS = 'GET_VOTES_SUCCESS';
export const GET_VOTES_FAILURE = 'GET_VOTES_FAILURE';

export const GET_STORIES_REQUEST = 'GET_STORIES_REQUEST';
export const GET_STORIES_SUCCESS = 'GET_STORIES_SUCCESS';
export const GET_STORIES_FAILURE = 'GET_STORIES_FAILURE';

export const CREATE_SPRINT_REQUEST = 'CREATE_SPRINT_REQUEST';
export const CREATE_SPRINT_SUCCESS = 'CREATE_SPRINT_SUCCESS';
export const CREATE_SPRINT_FAILURE = 'CREATE_SPRINT_FAILURE';

export const GET_SPRINT_REQUEST = 'GET_SPRINT_REQUEST';
export const GET_SPRINT_SUCCESS = 'GET_SPRINT_SUCCESS';
export const GET_SPRINT_FAILURE = 'GET_SPRINT_FAILURE';

export const MASTER = 'poker-planning-as-scrum-master';
export const DEVELOPER = 'poker-planning-as-developer';
export const HOME = 'poker-planning-add-story-list';
